FROM ubuntu:22.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    coreutils findutils grep sed gawk \
    procps psmisc \
    net-tools iproute2 iputils-ping curl wget \
    vim-tiny \
    man-db less \
    bc jq \
    && rm -rf /var/lib/apt/lists/*
RUN useradd -m -s /bin/bash learner
WORKDIR /home/learner
